# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models
import utils.image_thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170421_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', utils.image_thumbs.ImageWithThumbsField(blank=True, upload_to=posts.models.upload_location)),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
