# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models
import utils.image_thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170425_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=utils.image_thumbs.ImageWithThumbsField(blank=True, height_field='height', null=True, upload_to=posts.models.upload_location, width_field='width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
